{
    "name": "Gremio de Vialidad de Córdoba (AR)",
    "summary": """
        Instala todos los módulos necesarios para la gestión del
        Gremio de Vialidad de Córdoba Argentina.
    """,
    "sequence": 14,
    "author": "FMP Solutions S.A.S.",
    "website": "https://github.com/MarvinSoftwareSolutions/odoo-vialidad-cordoba",
    "license": "GPL-3",
    "category": "Accounting & Finance",
    "version": "16.0.0.0.0",
    "depends": [
        "account_check_printing",
        "account_edi_ubl_cii",
        "account_payment_invoice_online_payment_patch",
        "account_payment_ux",
        "account_sequence",
        "analytic",
        "auth_signup",
        "auth_totp_mail",
        "auth_totp_portal",
        "base_import",
        "base_install_request",
        "base_vat",
        "bus",
        "contacts",
        "google_gmail",
        "http_routing",
        "l10n_ar_afipws_fe",
        "l10n_ar_bank",
        "l10n_ar_reports",
        "l10n_ar_ux",
        "mail_bot",
        "partner_autocomplete",
        "privacy_lookup",
        "resource",
        "road_union_affiliation",
        "snailmail_account",
        "spreadsheet_account",
        "spreadsheet_dashboard_account",
        "spreadsheet_dashboard_stock_account",
        "stock_account_ux",
        "stock_sms",
        "union_affiliation",
        "web_kanban_gauge",
        "web_tour",
        "web_unsplash",
    ],
    "data": [
        "security/accounting_full_access.xml"
    ],
    "qweb": [],
    "assets": {},
    "installable": True,
    "auto_install": False,
    "application": True,
}
